branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: null
    group_suffix: null
global:
  application_name: app
  branch: null
  default_ec2_keyname: AdamKey
  default_platform: docker
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
